# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\LSS\LSS\Josephus problem\show\UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(998, 649)
        self.file_style = QtWidgets.QComboBox(Form)
        self.file_style.setGeometry(QtCore.QRect(150, 50, 161, 41))
        self.file_style.setObjectName("file_style")
        self.file_style.addItem("")
        self.file_style.addItem("")
        self.file_style.addItem("")
        self.file_style.addItem("")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(10, 280, 391, 361))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(100, 250, 121, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 111, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(550, 60, 81, 18))
        self.label_3.setObjectName("label_3")
        self.start_number = QtWidgets.QLineEdit(Form)
        self.start_number.setGeometry(QtCore.QRect(660, 60, 113, 25))
        self.start_number.setObjectName("start_number")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(550, 120, 81, 18))
        self.label_4.setObjectName("label_4")
        self.step_number = QtWidgets.QLineEdit(Form)
        self.step_number.setGeometry(QtCore.QRect(660, 110, 113, 25))
        self.step_number.setObjectName("step_number")
        self.start_josephus = QtWidgets.QPushButton(Form)
        self.start_josephus.setGeometry(QtCore.QRect(760, 220, 181, 71))
        self.start_josephus.setObjectName("start_josephus")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(560, 390, 81, 18))
        self.label_5.setObjectName("label_5")
        self.select_file = QtWidgets.QPushButton(Form)
        self.select_file.setGeometry(QtCore.QRect(70, 110, 211, 51))
        self.select_file.setObjectName("select_file")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(10, 190, 101, 18))
        self.label_6.setObjectName("label_6")
        self.file_name = QtWidgets.QLineEdit(Form)
        self.file_name.setGeometry(QtCore.QRect(100, 180, 251, 41))
        self.file_name.setObjectName("file_name")
        self.show_result = QtWidgets.QTextEdit(Form)
        self.show_result.setGeometry(QtCore.QRect(650, 380, 311, 107))
        self.show_result.setObjectName("show_result")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(570, 230, 141, 51))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.file_style.setItemText(0, _translate("Form", "csv文件"))
        self.file_style.setItemText(1, _translate("Form", "xlsx文件"))
        self.file_style.setItemText(2, _translate("Form", "txt文件"))
        self.file_style.setItemText(3, _translate("Form", "json文件"))
        self.label.setText(_translate("Form", "人员信息显示"))
        self.label_2.setText(_translate("Form", "输入文件类型"))
        self.label_3.setText(_translate("Form", "起始位置"))
        self.label_4.setText(_translate("Form", "步长"))
        self.start_josephus.setText(_translate("Form", "约瑟夫环开始"))
        self.label_5.setText(_translate("Form", "结果显示"))
        self.select_file.setText(_translate("Form", "选择文件"))
        self.label_6.setText(_translate("Form", "文件路径："))
        self.pushButton.setText(_translate("Form", "设置"))
